version: '3.8'

services:
  app:
    build:
      context: .
      target: local
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - '9050:80'
